name: Build & Publish RSS (Globe only)

on:
  workflow_dispatch:      # manual run
  schedule:
    - cron: "0 * * * *"   # hourly

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Globe-only RSS
        run: |
          python scripts/merge_rss.py

      - name: Commit & push rss.xml
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/rss.xml"
          message: "chore: update GlobeNewswire-only feed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
